package:
  version: 0.1
  repo_name: cheese-chatter
  src_repo: cheese
  author_email: aangel.maragones@outlook.com
  author_user_name: eiingeeel
  description: Cheese Chatter is an LLM app prepare to be used by a Telegram bot.

logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'
  log_file: 'cheese.log'

ollama:
  model: llama3.1
  temperature: 0
  embeddings: llama3.1

azureopenai:
  temperature: 0

launch:
  model: azureopenai
  embeddings: None
  turbo_model: None
