logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  datefmt: '%Y-%m-%d %H:%M:%S'
  log_file: 'cheese.log'

ollama:
  model: llama3.1
  temperature: 0

azureopenai:
  temperature: 0

launch:
  model: azureopenai
  embeddings: None
  turbo_model: None
